import Head from 'next/head'
import Image from 'next/image'
import { Button } from '@material-ui/core'
import {auth, provider} from '../firebase'

function Login() {

    const SignIn = () => {
       auth.signInWithPopup(provider)
    }

    return (
        <div>
            <Head>
                <title>Whatsapp-clone Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="https://upload.wikimedia.org/wikipedia/commons/6/6b/WhatsApp.svg" />
            </Head>

            <div className="sm:w-1/3 w-full bg-white h-screen m-auto">
                <div className="text-center flex flex-col pt-10">
                <Image 
                    src="https://upload.wikimedia.org/wikipedia/commons/6/6b/WhatsApp.svg"
                    width={300}
                    height={300}
                />
                <Button variant="outlined" size="large" onClick={SignIn}>Sign in with Google</Button>
                </div>

            </div>

        </div>
  )
}

export default Login
